fragen = [
    {"frage": "Ist die Freiheitsstatue in New York?", "antwort": "Ja"},
    {"frage": "Wurde die Pyramide von Gizeh in Ägypten gebaut?", "antwort": "Ja"},
    {"frage": "War Albert Einstein ein Musiker?", "antwort": "Nein"},
    {"frage": "Liegt der Amazonas in Afrika?", "antwort": "Nein"},
    {"frage": "Ist Französisch eine Amtssprache in Kanada?", "antwort": "Ja"},
    {"frage": "Hat Beethoven die Mona Lisa gemalt?", "antwort": "Nein"},
    {"frage": "Gehört die Sahara zu den größten Wüsten der Welt?", "antwort": "Ja"},
    {"frage": "Liegt die Stadt Paris in Italien?", "antwort": "Nein"},
    {"frage": "Ist der Eiffelturm aus Holz gebaut?", "antwort": "Nein"},
    {"frage": "Ist Fußball eine olympische Sportart?", "antwort": "Ja"},
    {"frage": "Hat die Antarktis Einwohner?", "antwort": "Nein"},
    {"frage": "Wurde die Berliner Mauer 1989 abgerissen?", "antwort": "Ja"},
    {"frage": "Gibt es eine Stadt namens Rom in Europa?", "antwort": "Ja"},
    {"frage": "Liegt der Mount Everest in Südamerika?", "antwort": "Nein"},
    {"frage": "Wurde die Bibel im Mittelalter geschrieben?", "antwort": "Nein"},
    {"frage": "Hat die Erde sieben Kontinente?", "antwort": "Ja"},
    {"frage": "Liegt das Mittelmeer in Asien?", "antwort": "Nein"},
    {"frage": "War Mozart ein berühmter Komponist?", "antwort": "Ja"},
    {"frage": "Ist der Nil der längste Fluss der Welt?", "antwort": "Ja"},
    {"frage": "War Napoleon ein König von Deutschland?", "antwort": "Nein"},
    {
        "frage": "Wurde das erste Flugzeug von den Gebrüdern Wright gebaut?",
        "antwort": "Ja",
    },
    {"frage": "Gibt es mehr als 190 Länder auf der Welt?", "antwort": "Ja"},
    {"frage": "Ist Australien eine Insel?", "antwort": "Ja"},
    {"frage": "Lebten die Dinosaurier vor den Menschen?", "antwort": "Ja"},
    {"frage": "Hat der Mond eine Atmosphäre wie die Erde?", "antwort": "Nein"},
    {"frage": "Liegt der Taj Mahal in Indien?", "antwort": "Ja"},
    {"frage": "Hat Deutschland eine Königin?", "antwort": "Nein"},
    {"frage": "War die Titanic ein Flugzeug?", "antwort": "Nein"},
    {"frage": "Gibt es mehr Süßwasser als Salzwasser auf der Erde?", "antwort": "Nein"},
    {"frage": "Liegt der Grand Canyon in den USA?", "antwort": "Ja"},
]
