Trinkgeld = int(input(("Bitte wählen Sie, wie viel Trinkgeld Sie geben möchten: 5%, 10%, 15%:\n")))
Total = Betrag + ((Betrag*Trinkgeld)/100)
Personenanzahl = int(input(("Wie viele Personen:\n")))
prokopf = round((Total/Personenanzahl),2)
print(f"Der pro Kopf zu zahlende Betrag: {prokopf}")